set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Bundle "Lokaltog/vim-powerline"
Bundle "tomasr/molokai"
Bundle 'Valloric/YouCompleteMe'
call vundle#end()
filetype plugin indent on

map <silent> <F2> :NERDTreeToggle<CR>

colorscheme molokai
set nu
syntax on
set autoindent
